//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECommerceWebApp.ItemListingServiceRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ItemListingServiceRef.IItemListingService")]
    public interface IItemListingService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IItemListingService/GetItems", ReplyAction="http://tempuri.org/IItemListingService/GetItemsResponse")]
        ItemListingService.Item[] GetItems(string searchTerm, int page, int pageSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IItemListingService/GetItems", ReplyAction="http://tempuri.org/IItemListingService/GetItemsResponse")]
        System.Threading.Tasks.Task<ItemListingService.Item[]> GetItemsAsync(string searchTerm, int page, int pageSize);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IItemListingServiceChannel : ECommerceWebApp.ItemListingServiceRef.IItemListingService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ItemListingServiceClient : System.ServiceModel.ClientBase<ECommerceWebApp.ItemListingServiceRef.IItemListingService>, ECommerceWebApp.ItemListingServiceRef.IItemListingService {
        
        public ItemListingServiceClient() {
        }
        
        public ItemListingServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ItemListingServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ItemListingServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ItemListingServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ItemListingService.Item[] GetItems(string searchTerm, int page, int pageSize) {
            return base.Channel.GetItems(searchTerm, page, pageSize);
        }
        
        public System.Threading.Tasks.Task<ItemListingService.Item[]> GetItemsAsync(string searchTerm, int page, int pageSize) {
            return base.Channel.GetItemsAsync(searchTerm, page, pageSize);
        }
    }
}
