//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace G21Assignment5.BuyerServiceRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Buyer", Namespace="http://schemas.datacontract.org/2004/07/BuyerService")]
    [System.SerializableAttribute()]
    public partial class Buyer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HashedPwField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HashedPw {
            get {
                return this.HashedPwField;
            }
            set {
                if ((object.ReferenceEquals(this.HashedPwField, value) != true)) {
                    this.HashedPwField = value;
                    this.RaisePropertyChanged("HashedPw");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BuyerServiceRef.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getBuyers", ReplyAction="http://tempuri.org/IService1/getBuyersResponse")]
        G21Assignment5.BuyerServiceRef.Buyer[] getBuyers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getBuyers", ReplyAction="http://tempuri.org/IService1/getBuyersResponse")]
        System.Threading.Tasks.Task<G21Assignment5.BuyerServiceRef.Buyer[]> getBuyersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getBuyerName", ReplyAction="http://tempuri.org/IService1/getBuyerNameResponse")]
        string getBuyerName(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getBuyerName", ReplyAction="http://tempuri.org/IService1/getBuyerNameResponse")]
        System.Threading.Tasks.Task<string> getBuyerNameAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addBuyer", ReplyAction="http://tempuri.org/IService1/addBuyerResponse")]
        bool addBuyer(string email, string hashedPw, string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addBuyer", ReplyAction="http://tempuri.org/IService1/addBuyerResponse")]
        System.Threading.Tasks.Task<bool> addBuyerAsync(string email, string hashedPw, string name);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : G21Assignment5.BuyerServiceRef.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<G21Assignment5.BuyerServiceRef.IService1>, G21Assignment5.BuyerServiceRef.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public G21Assignment5.BuyerServiceRef.Buyer[] getBuyers() {
            return base.Channel.getBuyers();
        }
        
        public System.Threading.Tasks.Task<G21Assignment5.BuyerServiceRef.Buyer[]> getBuyersAsync() {
            return base.Channel.getBuyersAsync();
        }
        
        public string getBuyerName(string email) {
            return base.Channel.getBuyerName(email);
        }
        
        public System.Threading.Tasks.Task<string> getBuyerNameAsync(string email) {
            return base.Channel.getBuyerNameAsync(email);
        }
        
        public bool addBuyer(string email, string hashedPw, string name) {
            return base.Channel.addBuyer(email, hashedPw, name);
        }
        
        public System.Threading.Tasks.Task<bool> addBuyerAsync(string email, string hashedPw, string name) {
            return base.Channel.addBuyerAsync(email, hashedPw, name);
        }
    }
}
