//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECommerceWebApp.SellerServiceRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SellerServiceRef.ISellerService")]
    public interface ISellerService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISellerService/CreateSeller", ReplyAction="http://tempuri.org/ISellerService/CreateSellerResponse")]
        int CreateSeller(string email, string hashedPassword, string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISellerService/CreateSeller", ReplyAction="http://tempuri.org/ISellerService/CreateSellerResponse")]
        System.Threading.Tasks.Task<int> CreateSellerAsync(string email, string hashedPassword, string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISellerService/UpdateSeller", ReplyAction="http://tempuri.org/ISellerService/UpdateSellerResponse")]
        bool UpdateSeller(int sellerId, string newEmail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISellerService/UpdateSeller", ReplyAction="http://tempuri.org/ISellerService/UpdateSellerResponse")]
        System.Threading.Tasks.Task<bool> UpdateSellerAsync(int sellerId, string newEmail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISellerService/CreateListing", ReplyAction="http://tempuri.org/ISellerService/CreateListingResponse")]
        int CreateListing(int sellerId, string itemName, decimal price);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISellerService/CreateListing", ReplyAction="http://tempuri.org/ISellerService/CreateListingResponse")]
        System.Threading.Tasks.Task<int> CreateListingAsync(int sellerId, string itemName, decimal price);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISellerServiceChannel : ECommerceWebApp.SellerServiceRef.ISellerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SellerServiceClient : System.ServiceModel.ClientBase<ECommerceWebApp.SellerServiceRef.ISellerService>, ECommerceWebApp.SellerServiceRef.ISellerService {
        
        public SellerServiceClient() {
        }
        
        public SellerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SellerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SellerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SellerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int CreateSeller(string email, string hashedPassword, string name) {
            return base.Channel.CreateSeller(email, hashedPassword, name);
        }
        
        public System.Threading.Tasks.Task<int> CreateSellerAsync(string email, string hashedPassword, string name) {
            return base.Channel.CreateSellerAsync(email, hashedPassword, name);
        }
        
        public bool UpdateSeller(int sellerId, string newEmail) {
            return base.Channel.UpdateSeller(sellerId, newEmail);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateSellerAsync(int sellerId, string newEmail) {
            return base.Channel.UpdateSellerAsync(sellerId, newEmail);
        }
        
        public int CreateListing(int sellerId, string itemName, decimal price) {
            return base.Channel.CreateListing(sellerId, itemName, price);
        }
        
        public System.Threading.Tasks.Task<int> CreateListingAsync(int sellerId, string itemName, decimal price) {
            return base.Channel.CreateListingAsync(sellerId, itemName, price);
        }
    }
}
